version: '3'
services:
  web:
    build: . # Tìm Dockerfile ở thư mục hiện hành
    container_name: web_lab02
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/lab02 # Match thư mục hiện hành với thư mục lab01 trong máy ảo
    entrypoint: sh /lab02/startup.sh
    links:
      - db
  db:
    image: postgres
    container_name: db_lab02
    env_file: .env